### PR TITLE
fix: Make sure coalescelist does not throw error

### LINKED ISSUE #17: coalescelist does not allow all lists to be empty
There was a change in the behaviour of the coalescelist function in terraform 0.12 (see [this issue](https://github.com/hashicorp/terraform/issues/21370)) that means that if you pass it all empty lists it will throw an error. This poses a problem for this module on lines [like this](https://github.com/cloudposse/terraform-aws-alb-target-group-cloudwatch-sns-alarms/blob/master/main.tf#L49) if you are relying on default values.

### PR DESCRIPTION
**Pull request by k911**
- Also, add tags to alarms

Fixes #17

### CODE REVIEW

**Comment by k911** [comment]
@aknysh Could you please take a look?

**Comment by nicgordon** [comment]
Pretty keen for this one to be merged so we can stop using a forked version of https://github.com/cloudposse/terraform-aws-ecs-web-app. Does anyone have any capacity to release this? 🙏

**Comment by k911** [comment]
@maximmi I've updated readme

**Comment by k911** [comment]
@maximmi Anything more to be done?

**Pull request merged**
